CREATE TABLE Users (
    userId INTEGER(10) NOT NULL PRIMARY KEY,
    name VARCHAR(50) NOT NULL,
    address VARCHAR(255)
);
CREATE TABLE Accounts (
    accountId INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    userId INTEGER(10) NOT NULL,
    balance DECIMAL(15,3) NOT NULL,
    currency VARCHAR(10) NOT NULL,
    FOREIGN KEY(userId) REFERENCES Users(userId)
);
CREATE TABLE Transactions (
    transactionId INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    accountId INTEGER(10) NOT NULL,
    amount DECIMAL(15,3) NOT NULL,
    FOREIGN KEY(accountId) REFERENCES Accounts(accountId)
);